name: 🐛 Bug Report
description: File a bug report to help us improve BEM
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you've completed these steps
      options:
        - label: I've searched existing issues and this isn't a duplicate
          required: true
        - label: I'm using the latest stable version of BEM
          required: true
        - label: I've read the troubleshooting guide
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Configure BEM with...
        2. Run command...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 13.0]
        - Python Version: [e.g., 3.11.5]
        - BEM Version: [e.g., 2.0.0]
        - PyTorch Version: [e.g., 2.1.0]
        - CUDA Version: [e.g., 12.1] (if using GPU)
        - GPU: [e.g., NVIDIA RTX 4090] (if applicable)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please include relevant error messages, stack traces, or log outputs
      placeholder: Paste error messages and stack traces here...
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: If applicable, include your BEM configuration
      placeholder: |
        # Include relevant configuration files (YAML/JSON)
        # Remove any sensitive information
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant information
      placeholder: Any additional information that might help...