# GitHub Pages Deployment Workflow
# Builds and deploys comprehensive documentation site

name: Deploy Documentation to Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'examples/**'
      - 'src/**/*.py'  # For API docs generation
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Weekly rebuild to keep docs fresh

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git info
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r docs/requirements.txt
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Generate API Documentation
        run: |
          # Generate API docs from source code
          sphinx-apidoc -o docs/api src/
          
          # Generate examples documentation
          python scripts/generate_examples_docs.py
          
          # Generate performance benchmarks
          python scripts/generate_benchmark_docs.py
      
      - name: Build Documentation
        run: |
          cd docs
          make html
          
          # Copy additional assets
          cp -r ../examples/_build/html/* _build/html/examples/ 2>/dev/null || true
          cp -r ../benchmarks/_build/html/* _build/html/benchmarks/ 2>/dev/null || true
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2